version: "3.8"

services:
  postgres-db:
    image: postgres:alpine
    container_name: pgcont
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data-vol:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 5s
      retries: 5

  backend:
    image: node:22-alpine3.22
    container_name: express-backend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend/:/app
      - /app/node_modules
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pg-data-vol: {}
